# flake8: noqa
# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-21 04:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wings_main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='id_string',
            field=models.BigIntegerField(help_text=b'ID string should contain exactly 12 digits.', unique=True),
        ),
    ]
