# flake8: noqa
# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-21 04:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ssnmtreeblock', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ssnmtreeblock',
            name='editable_support_types',
            field=models.ManyToManyField(blank=True, help_text=b'Support Types you can *edit* on this page.', related_name='blocks_where_you_can_edit_this_support_type', to='ssnmtreeblock.SsnmTreeSupportType'),
        ),
        migrations.AlterField(
            model_name='ssnmtreeblock',
            name='visible_support_types',
            field=models.ManyToManyField(blank=True, help_text=b'Support Types you can *see* on this page.', related_name='blocks_where_you_can_see_this_support_type', to='ssnmtreeblock.SsnmTreeSupportType'),
        ),
    ]
